/**
 * This script was generated by Loon to simulate http requests.
 * Modified: Authorization 从 $persistentStore 自动读取
 * Modified: 签到前检测 JWT 过期时间，快过期时通知提醒
 */

const $env = (function () {
  const isLoon = typeof $loon !== "undefined";
  const isSurge = typeof $httpClient !== "undefined" && !isLoon;
  const isQX = typeof $task !== "undefined";
  return { isLoon, isSurge, isQX, isCli: isLoon || isSurge };
})();

function notify(title, sub, body) {
  if ($env.isQX && typeof $notify === "function") {
    $notify(title, sub, body);
  } else if (typeof $notification !== "undefined" && $notification.post) {
    $notification.post(title, sub, body);
  } else if (typeof $notify === "function") {
    $notify(title, sub, body);
  }
}

function finish() { $done(); }

// 解析 JWT payload
function parseJwtPayload(token) {
  try {
    var parts = token.split(".");
    if (parts.length < 2) return null;
    var b64 = parts[1].replace(/-/g, "+").replace(/_/g, "/");
    while (b64.length % 4 !== 0) b64 += "=";
    return JSON.parse(atob(b64));
  } catch (e) {
    return null;
  }
}

// 从 persistentStore 读取 Token（由 GetToken 脚本自动写入）
var STORE_KEY = "XYHG_Authorization";
var savedAuth = $persistentStore.read(STORE_KEY);

if (!savedAuth) {
  notify("鑫耀光环签到", "缺少 Token", "请先打开小程序触发 Token 抓取脚本");
  finish();
} else {

  // === JWT 过期检测 ===
  var jwtToken = savedAuth.replace(/^Bearer\s+/i, "");
  var payload = parseJwtPayload(jwtToken);

  if (payload && payload.exp) {
    var nowSec = Math.floor(Date.now() / 1000);
    var remainSec = payload.exp - nowSec;
    var remainHour = Math.round(remainSec / 3600 * 10) / 10;

    if (remainSec <= 0) {
      // 已过期
      notify("鑫耀光环签到", "Token 已过期", "请打开小程序刷新 Token 后重试");
      finish();
    } else if (remainHour <= 6) {
      // 6 小时内即将过期，提醒但继续签到
      notify("鑫耀光环 Token", "即将过期（剩余 " + remainHour + " 小时）", "请尽快打开小程序刷新 Token");
    }
  }

  // === 继续执行签到 ===
  let url = "https://crm.theringlive.com:13881/api/Sign/SignIn";
  let headers = {
      'content-type':'application/json',
      'Accept-Encoding':'gzip,compress,br,deflate',
      'User-Agent':'Mozilla/5.0 (iPhone; CPU iPhone OS 26_5 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Mobile/15E148 MicroMessenger/8.0.75(0x18004b2f) NetType/WIFI Language/zh_CN',
      'Connection':'keep-alive',
      'buildingid':'8812',
      'Authorization': savedAuth,
      'Content-Length':'4',
      'Referer':'https://servicewechat.com/wx8afc1deed936cb45/58/page-frame.html',
      'Host':'crm.theringlive.com:13881',
  };

  let body = "null";
  var params = {
      url:url,
      timeout:5000,
      headers:headers,
      body:body,
  };

  $httpClient.post(params, function(errormsg,response,data) {
      if (errormsg) {
          notify("鑫耀光环签到", "请求异常", "" + errormsg);
      } else {
          let bodyPreview = (data || "").slice(0, 500);
          if (response.status === 200) {
              notify("鑫耀光环签到", "签到成功", bodyPreview);
          } else {
              let msg = "Status: " + response.status;
              try {
                  const parsed = JSON.parse(data);
                  if (parsed.msg) {
                      msg = parsed.msg;
                  } else if (parsed.message) {
                      msg = parsed.message;
                  }
              } catch (e) {}
              notify("鑫耀光环签到", "签到失败 (" + response.status + ")", msg + (bodyPreview ? "\n" + bodyPreview : ""));
          }
      }
      finish();
  });
}
